print('“I affirm that I have carried out my academic endeavors with full academic honesty. [Signed, Jane Doe]"')
#Question 1.a
print('There are two ways of spreading light:\n\nTo be the "candle", or the "mirror" that reflects it.')
#Question 1.b
print('"There are two ways of spreading light:\n\t1. To be the candle, or\n\t2. the mirror that reflects it."')
#Question 1.c
day = input()
month = input()
year = input()
print("Enter your birthday\nDay:", day,'\nMonth:', month,'\nYear:', year,'\n\nCongratulations!Your birthday is', month,'-', day, '-', year,'\nYou are', '(',2019,'-',year,')','=',2019-int(year),'years old.')
#Question 1.d
num1 = int(input())
num2 = int(input())
num3 = int(input())
print('Enter three integers:','\nInteger 1:', num1,'\nInteger 2:', num2,'\nInteger 3:', num3,'\nMath operations:\n',num1,'+',num2,'+',num3,'=',num1+num2+num3,'\n',num1,'-',num2,'-',num3,'=',num1-num2-num3,'\n',num1,'*',num2,'*',num3,'=',num1*num2*num3,'\nNum1*(Num2+Num3) is\n\t','not equal to\n','Num1*Num2+Num3\n\t\tProof:\n\t\t=====\n',num1,'*(',num2,'+',num3,')=',num1*num2+num3,'\n\tis not equal to\n',num1,'*',num2,'+',num3,'=',num1*num2+num3)
#Question 2
name1 = input()
age1 = input()
year1 = input()
gpa1 = input()
gender1 = input()
id1 = input()
credit1 = input()
name2 = input()
age2 = input()
year2 = input()
gpa2 = input()
gender2 = input()
id2 = input()
credit2 = input()
print('First student:\n Enter your\n Name:',name1,'\n Age:',age1,'\n Year:',year1,'\n Gpa:',gpa1,'\n Gender F(emale) M(ale):',gender1,'\n Id:',id1,'\n #credits you have taken this semester:',credit1,'\n\nSecond student:\n Enter your\n Name:',name2,'\n Age:',age2,'\n Year:',year2,'\n Gpa:',gpa2,'\n Gender F(emale) M(ale):',gender2,'\n Id:',id2,'\n #credits you have taken this semester:',credit2,'\n\nReport:\n============================================================\nFirst student:\n---------\nName Surname:',name1, '\t\tGender\t\t:',gender1,'\nAge\t\t:',age1, '\t\tID\t\t:',id1,'\nYear\t\t:',year1, '\t\tGPA\t\t:',gpa1,'\nYou have taken',credit1,'credits.\n============================================================\nSecond student:\n---------\nName Surname:',name2, '\t\tGender\t\t:',gender2,'\nAge\t\t:',age2, '\t\tID\t\t:',id2,'\nYear\t\t:',year2, '\t\tGPA\t\t:',gpa2,'\nYou have taken',credit2,'credits.')
